// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Atlas.Api.Data;

#nullable disable

namespace Atlas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111120000_MakeMessageTemplateKeyNullable")]
    partial class MakeMessageTemplateKeyNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally left empty.
            // Snapshot is owned by AppDbContextModelSnapshot.
        }
    }
}
